In [1]:
import pandas as pd
import tabula
file = "filename.pdf"
path = 'table.pdf'
df = tabula.read_pdf(path, pages = '1', multiple_tables = True)
print(df)

[             0             1          2            3             4  \
0          NaN           NaN        NaN          NaN           NaN
1          NaN           NaN        NaN      Ballots           NaN
2   Disability           NaN    Ballots          NaN           NaN
3          NaN  Participants        NaN  Incomplete/           NaN
4     Category           NaN  Completed          NaN      Accuracy
5          NaN           NaN        NaN   Terminated           NaN
6          NaN           NaN        NaN          NaN           NaN
7        Blind             5          1            4    34.5%, n=1
8   Low Vision             5          2            3     98.3% n=2
9          NaN           NaN        NaN          NaN  (97.7%, n=3)
10   Dexterity             5          4            1    98.3%, n=4
11    Mobility             3          3            0    95.4%, n=3

                  5
0           Results
1               NaN
2               NaN
3               NaN
4           Time to
5               NaN
6          complete
7     1199 sec, n=1
8     1716 sec, n=3
9   (1934 sec, n=2)
10  1672.1 sec, n=4
11    1416 sec, n=3  ]

In [2]:
df=tabula.read_pdf("table.pdf", pages=1)

# in order to print first 5 lines of Table
df.head()

   Unnamed: 0    Unnamed: 1 Unnamed: 2   Unnamed: 3 Unnamed: 4  Results
0         NaN           NaN        NaN      Ballots        NaN      NaN
1  Disability           NaN    Ballots          NaN        NaN      NaN
2         NaN  Participants        NaN  Incomplete/        NaN      NaN
3    Category           NaN  Completed          NaN   Accuracy  Time to
4         NaN           NaN        NaN   Terminated        NaN      NaN

In [156]:
from tabula import read_pdf
df=read_pdf('/home/am/Downloads/read.pdf')
import pandas as pd
df1=pd.DataFrame(df)
df1

,Name :,MUKESH SHARMA,Unnamed: 2,Unnamed: 3,FOLIO :91013119452,Unnamed: 5,CAN:,Unnamed: 7,Unnamed: 8
0,NaN,NaN,NaN,NaN,BOID :1208160010642423,NaN,UMRN :,NaN,NaN
1,Address :,H No 820 Gali No 6 Batala Road,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,New Rajesh Nagar,NaN,NaN,Bank Name : STATE BANK OF INDIA,NaN,NaN,NaN,NaN
3,NaN,Amritsar,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Punjab,PIN : 143001,NaN,Bank A/c No: XXXXXXX4660,NaN,A/c Type:,SAVINGS,NaN
5,NaN,NaN,NaN,NaN,Branch: AMRITSAR,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,Payout Type: Electronic,NaN,IFSC Code :,SBIN0008016,NaN
7,NaN,NaN,NaN,NaN,Multiple Bank Reg: Not Registered,NaN,MICR Code:,143002005,NaN
8,Phone :,8054619283,Mobile : 8054619283,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,PAN No,NaN,CKYC,KYC,#FATCA
10,Email :,BHARDWAJ.MUKESH91@GMAIL.COM,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,1st Holder KSTPS1360G,NaN,NaN,NaN,Registered
12,2nd Holder :,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,2nd Holder,NaN,NaN,NaN,NaN
14,3rd Holder :,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,3rd Holder,NaN,NaN,NaN,NaN
16,ARN (Latest/Last) :,NaN,000000-0 Advisory (RIA) :,INZ000031633,Guardian,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,POA : NA,NaN,Nominee : 1.,NaN,NaN
18,Broker Name,:,DIRECT,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,2.,NaN,NaN
20,Sub-Broker,:,NaN,NaN,NaN,NaN,3.,NaN,NaN
21,NaN,NaN,NaN,NaN,UBO : NA,NaN,NaN,NaN,NaN
22,EUIN,:,NaN,NaN,Mode of Holding : SINGLE,NaN,Status:,NaN,INDIVIDUAL
23,# It is mandatory for all investors (new and ...,w,. k a r v y mf s . c o m,/ k a r v y / f a c t a h o m,e . a s p x,NaN,NaN,NaN,NaN
24,or by submitting a duly filled and signed appl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,In case there is any change in your KYC inform...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Portfolio Summary as on 26/09/2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Scheme Name Units Allotted Cost of Investment NAV,NaN,NaN,Current Value,NaN,NaN,NaN,NaN,NaN
28,Motilal Oswal Multicap 35 Fund - Direct Growth...,NaN,NaN,NaN,"3,158.00",NaN,NaN,NaN,NaN
29,"Total: 3,000.00",NaN,NaN,NaN,"3,158.00",NaN,NaN,NaN,NaN
30,Detailed Transaction Summary,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Scheme Motilal Oswal Multicap 35 Fund - Direct...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,Date Transaction Type Amount(INR) NAV(INR),NaN,Units,NaN,Unit Balance,NaN,NaN,NaN,NaN
33,"18/07/2019 Purchase(NAV Dt.18/07/2019) 1,000.0...",NaN,36.790,NaN,36.790,NaN,NaN,NaN,NaN
34,"16/08/2019 Purchase(NAV Dt.16/08/2019) 1,000.0...",NaN,38.500,NaN,75.290,NaN,NaN,NaN,NaN
35,"16/09/2019 Purchase(NAV Dt.16/09/2019) 1,000.0...",NaN,37.945,NaN,113.235,NaN,NaN,NaN,NaN
36,Balance Units: 113.235 Pledged/Blocked Units: ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [111]:
pan=[]
for i in df1['FOLIO :91013119452']:
    try:

        a=[]
        
        for j in i.split():
            a.append(i.split())
        for k in a:
            if k[0]=='PAN':
                pan.append(k[0]+' '+k[1])
                break
            if k[0]=='1st':
                find[pan[0]]=k[-1]
                break
            
          
    except:
        pass
find

{'Name': 'MUKESH SHARMA',
 'FOLIO': '91013119452',
 'BOID': ':1208160010642423',
 'Address': 'H No 820 Gali No 6 Batala Road,New Rajesh Nagar',
 'PIN': '143001',
 'Mobile': '8054619283',
 'PAN No': 'KSTPS1360G'}

In [112]:
find={}
pan=[]
find[df1.columns[0].split()[0]]=df1.columns[1]
find[df1.columns[4].split(':')[0].strip()]=df1.columns[4].split(':')[1].strip()
find[df1['FOLIO :91013119452'][0].split()[0].strip()]=df1['FOLIO :91013119452'][0].split()[1].strip()
for i in df1['Unnamed: 2']:
    try:
        a=[]
        for j in i.split():
            a.append(i.split())
        for k in a:
            if k[0]=='PIN':
                find[df1['Name :'][1].split()[0].strip()]=df1['MUKESH SHARMA'][1]+','+df1['MUKESH SHARMA'][2]
                find[k[0]]=k[-1]
                break
            if k[0]=='Mobile':
                find[k[0]]=k[-1]
                break
    except:
        pass
for i in df1['FOLIO :91013119452']:
    try:

        a=[]
        
        for j in i.split():
            a.append(i.split())
        for k in a:
            if k[0]=='PAN':
                pan.append(k[0]+' '+k[1])
                break
            if k[0]=='1st':
                find[pan[0]]=k[-1]
                break
            
          
    except:
        pass
find

find

{'Name': 'MUKESH SHARMA',
 'FOLIO': '91013119452',
 'BOID': ':1208160010642423',
 'Address': 'H No 820 Gali No 6 Batala Road,New Rajesh Nagar',
 'PIN': '143001',
 'Mobile': '8054619283',
 'PAN No': 'KSTPS1360G'}

In [105]:
for i in df1['FOLIO :91013119452']:
    try:
        pan=[]
        a=[]
        
        for j in i.split():
            a.append(i.split())
        for k in a:
            if k[0]=='PAN':
                pan.append(k[0]+' '+k[1])
                #print(pan[0])
                break
            if k[0]=='1st':
                a([k[-1]])
                #find[pan[0]]=k[-1]
                print(pan[0])
                print([k[-1]])
                #print(find)
                break
            
          
    except:
        pass

In [85]:
find

{'Name': 'MUKESH SHARMA',
 'FOLIO': '91013119452',
 'BOID': ':1208160010642423',
 'Address': 'H No 820 Gali No 6 Batala Road,New Rajesh Nagar',
 'PIN': '143001',
 'Mobile': '8054619283',
 'KSTPS1360G': 'KSTPS1360G'}

In [222]:
import easygui
import pandas as pd
from tabula import read_pdf
from PyPDF2 import PdfFileReader, PdfFileWriter

#encrypt passwrod protect file

file_path = easygui.fileopenbox()
password='KSTPS1360G'
with open(file_path, 'rb') as input_file, \
    open('new.pdf', 'wb') as output_file:
    reader = PdfFileReader(input_file)
    reader.decrypt(password)
    writer = PdfFileWriter()
    for i in range(reader.getNumPages()):
        writer.addPage(reader.getPage(i))
    writer.write(output_file)

In [289]:
from bs4 import BeautifulSoup
link='file:///home/am/.cache/.fr-y8KFyJ/3aabf7c8-0068-11ea-9d71-0cc47a792c0a_id_3aabf7c8-0068-11ea-9d71-0cc47a792c0a.html'
soup=BeautifulSoup(f.read(),'html.parser')

''

In [276]:
import requests
page=requests.get('https://www.researchgate.net/post/How_do_I_extract_the_content_from_dynamic_web_pages')

In [293]:
import codecs
f=codecs.open("/home/am/Downloads/new/3aabf7c8-0068-11ea-9d71-0cc47a792c0a_id_3aabf7c8-0068-11ea-9d71-0cc47a792c0a.html", 'r')
f=f.read()
soup=BeautifulSoup(f,'html.parser')

In [1]:
import camelot
tables = camelot.read_pdf('new.pdf')

In [10]:
tables
tables.export('foo.csv', f='csv', compress=True, multiple=True)
tables[0]
tables[0].parsing_report
tables[0].to_csv('foo.csv')
tables[0].df

In [35]:
pip install --user pdftotree

Collecting pdftotree
  Downloading https://files.pythonhosted.org/packages/0d/d1/5eaa6056319672bdd4c26a25d8294b814a74d5d0e0a0d276389469e0c542/pdftotree-0.4.0-py3-none-any.whl (53kB)
     |████████████████████████████████| 61kB 40kB/s eta 0:00:011     |██████████████████████████████▋ | 51kB 115kB/s eta 0:00:01
Requirement already satisfied: h5py in /home/am/.local/lib/python3.6/site-packages (from pdftotree) (2.10.0)
Collecting keras==2.0.8
  Downloading https://files.pythonhosted.org/packages/67/3f/d117d6e48b19fb9589369f4bdbe883aa88943f8bb4a850559ea5c546fefb/Keras-2.0.8-py2.py3-none-any.whl (276kB)
     |████████████████████████████████| 276kB 124kB/s eta 0:00:01
Requirement already satisfied: tensorflow in /home/am/.local/lib/python3.6/site-packages (from pdftotree) (2.0.0)
Requirement already satisfied: PyPDF2 in /home/am/.local/lib/python3.6/site-packages (from pdftotree) (1.26.0)
Requirement already satisfied: six in /home/am/.local/lib/python3.6/site-packages (from pdftotree) (1.12.0)
Requirement already satisfied: beautifulsoup4 in /home/am/.local/lib/python3.6/site-packages (from pdftotree) (4.8.0)
Requirement already satisfied: pandas in /home/am/.local/lib/python3.6/site-packages (from pdftotree) (0.25.3)
Requirement already satisfied: numpy in /home/am/.local/lib/python3.6/site-packages (from pdftotree) (1.17.2)
Requirement already satisfied: tabula-py in /home/am/.local/lib/python3.6/site-packages (from pdftotree) (1.4.1)
Requirement already satisfied: scipy in /home/am/.local/lib/python3.6/site-packages (from pdftotree) (1.3.1)
Requirement already satisfied: pdfminer.six in /home/am/.local/lib/python3.6/site-packages (from pdftotree) (20181108)
Requirement already satisfied: pillow in /usr/lib/python3/dist-packages (from pdftotree) (5.1.0)
Requirement already satisfied: future in /home/am/.local/lib/python3.6/site-packages (from pdftotree) (0.18.0)
Collecting wand
  Downloading https://files.pythonhosted.org/packages/3e/43/0fbca3a034c92f3ac989948a0920d0b4f6c0c3c3317769fcaac8dde57e35/Wand-0.5.7-py2.py3-none-any.whl (128kB)
     |████████████████████████████████| 133kB 540kB/s eta 0:00:01
Collecting sklearn
  Downloading https://files.pythonhosted.org/packages/1e/7a/dbb3be0ce9bd5c8b7e3d87328e79063f8b263b2b1bfa4774cb1147bfcd3f/sklearn-0.0.tar.gz
Requirement already satisfied: IPython in /home/am/.local/lib/python3.6/site-packages (from pdftotree) (7.8.0)
Collecting selectivesearch
  Downloading https://files.pythonhosted.org/packages/ad/f8/dac81bcfc2923144626e0361446caf92b9b7a79ff27ee7b01f762c364ba5/selectivesearch-0.4.tar.gz
Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (from keras==2.0.8->pdftotree) (3.12)
Requirement already satisfied: tensorflow-estimator<2.1.0,>=2.0.0 in /home/am/.local/lib/python3.6/site-packages (from tensorflow->pdftotree) (2.0.0)
Requirement already satisfied: keras-preprocessing>=1.0.5 in /home/am/.local/lib/python3.6/site-packages (from tensorflow->pdftotree) (1.1.0)
Requirement already satisfied: tensorboard<2.1.0,>=2.0.0 in /home/am/.local/lib/python3.6/site-packages (from tensorflow->pdftotree) (2.0.0)
Requirement already satisfied: wheel>=0.26 in /usr/lib/python3/dist-packages (from tensorflow->pdftotree) (0.30.0)
Requirement already satisfied: wrapt>=1.11.1 in /home/am/.local/lib/python3.6/site-packages (from tensorflow->pdftotree) (1.11.2)
Requirement already satisfied: opt-einsum>=2.3.2 in /home/am/.local/lib/python3.6/site-packages (from tensorflow->pdftotree) (3.1.0)
Requirement already satisfied: protobuf>=3.6.1 in /home/am/.local/lib/python3.6/site-packages (from tensorflow->pdftotree) (3.10.0)
Requirement already satisfied: gast==0.2.2 in /home/am/.local/lib/python3.6/site-packages (from tensorflow->pdftotree) (0.2.2)
Requirement already satisfied: termcolor>=1.1.0 in /home/am/.local/lib/python3.6/site-packages (from tensorflow->pdftotree) (1.1.0)
Requirement already satisfied: absl-py>=0.7.0 in /home/am/.local/lib/python3.6/site-packages (from tensorflow->pdftotree) (0.8.1)
Requirement already satisfied: google-pasta>=0.1.6 in /home/am/.local/lib/python3.6/site-packages (from tensorflow->pdftotree) (0.1.7)
Requirement already satisfied: keras-applications>=1.0.8 in /home/am/.local/lib/python3.6/site-packages (from tensorflow->pdftotree) (1.0.8)
Requirement already satisfied: grpcio>=1.8.6 in /home/am/.local/lib/python3.6/site-packages (from tensorflow->pdftotree) (1.24.1)
Requirement already satisfied: astor>=0.6.0 in /home/am/.local/lib/python3.6/site-packages (from tensorflow->pdftotree) (0.8.0)
Requirement already satisfied: soupsieve>=1.2 in /home/am/.local/lib/python3.6/site-packages (from beautifulsoup4->pdftotree) (1.9.4)
Requirement already satisfied: pytz>=2017.2 in /usr/lib/python3/dist-packages (from pandas->pdftotree) (2018.3)
Requirement already satisfied: python-dateutil>=2.6.1 in /usr/lib/python3/dist-packages (from pandas->pdftotree) (2.6.1)
Requirement already satisfied: distro in /home/am/.local/lib/python3.6/site-packages (from tabula-py->pdftotree) (1.4.0)
Requirement already satisfied: sortedcontainers in /home/am/.local/lib/python3.6/site-packages (from pdfminer.six->pdftotree) (2.1.0)
Requirement already satisfied: pycryptodome in /home/am/.local/lib/python3.6/site-packages (from pdfminer.six->pdftotree) (3.9.0)
Collecting scikit-learn
  Downloading https://files.pythonhosted.org/packages/a0/c5/d2238762d780dde84a20b8c761f563fe882b88c5a5fb03c056547c442a19/scikit_learn-0.21.3-cp36-cp36m-manylinux1_x86_64.whl (6.7MB)
     |████████████████████████████████| 6.7MB 58kB/s  eta 0:00:01     |████████████████████            | 4.2MB 1.3MB/s eta 0:00:02
Requirement already satisfied: pickleshare in /home/am/.local/lib/python3.6/site-packages (from IPython->pdftotree) (0.7.5)
Requirement already satisfied: pexpect; sys_platform != "win32" in /usr/lib/python3/dist-packages (from IPython->pdftotree) (4.2.1)
Requirement already satisfied: backcall in /home/am/.local/lib/python3.6/site-packages (from IPython->pdftotree) (0.1.0)
Requirement already satisfied: decorator in /home/am/.local/lib/python3.6/site-packages (from IPython->pdftotree) (4.4.0)
Requirement already satisfied: prompt-toolkit<2.1.0,>=2.0.0 in /home/am/.local/lib/python3.6/site-packages (from IPython->pdftotree) (2.0.10)
Requirement already satisfied: pygments in /home/am/.local/lib/python3.6/site-packages (from IPython->pdftotree) (2.4.2)
Requirement already satisfied: setuptools>=18.5 in /usr/lib/python3/dist-packages (from IPython->pdftotree) (39.0.1)
Requirement already satisfied: traitlets>=4.2 in /home/am/.local/lib/python3.6/site-packages (from IPython->pdftotree) (4.3.3)
Requirement already satisfied: jedi>=0.10 in /home/am/.local/lib/python3.6/site-packages (from IPython->pdftotree) (0.15.1)
Collecting scikit-image
  Downloading https://files.pythonhosted.org/packages/c8/bb/771800366f41d66eef51e4b80515f8ef7edab234a3f244fdce3bafe89b39/scikit_image-0.16.2-cp36-cp36m-manylinux1_x86_64.whl (26.5MB)
     |████████████████████████████████| 26.5MB 72kB/s  eta 0:00:01     |█████████████▌                  | 11.2MB 386kB/s eta 0:00:40     |███████████████████████████████▉| 26.4MB 162kB/s eta 0:00:01
Requirement already satisfied: markdown>=2.6.8 in /home/am/.local/lib/python3.6/site-packages (from tensorboard<2.1.0,>=2.0.0->tensorflow->pdftotree) (3.1.1)
Requirement already satisfied: werkzeug>=0.11.15 in /home/am/.local/lib/python3.6/site-packages (from tensorboard<2.1.0,>=2.0.0->tensorflow->pdftotree) (0.16.0)
Collecting joblib>=0.11
  Downloading https://files.pythonhosted.org/packages/8f/42/155696f85f344c066e17af287359c9786b436b1bf86029bb3411283274f3/joblib-0.14.0-py2.py3-none-any.whl (294kB)
     |████████████████████████████████| 296kB 85kB/s  eta 0:00:01
Requirement already satisfied: wcwidth in /home/am/.local/lib/python3.6/site-packages (from prompt-toolkit<2.1.0,>=2.0.0->IPython->pdftotree) (0.1.7)
Requirement already satisfied: ipython-genutils in /home/am/.local/lib/python3.6/site-packages (from traitlets>=4.2->IPython->pdftotree) (0.2.0)
Requirement already satisfied: parso>=0.5.0 in /home/am/.local/lib/python3.6/site-packages (from jedi>=0.10->IPython->pdftotree) (0.5.1)

Collecting imageio>=2.3.0
  Downloading https://files.pythonhosted.org/packages/1a/de/f7f985018f462ceeffada7f6e609919fbcc934acd9301929cba14bc2c24a/imageio-2.6.1-py3-none-any.whl (3.3MB)
     |████████████████████████████████| 3.3MB 629kB/s eta 0:00:01
Collecting PyWavelets>=0.4.0
  Downloading https://files.pythonhosted.org/packages/59/bb/d2b85265ec9fa3c1922210c9393d4cdf7075cc87cce6fe671d7455f80fbc/PyWavelets-1.1.1-cp36-cp36m-manylinux1_x86_64.whl (4.4MB)
     |████████████████████████████████| 4.4MB 75kB/s  eta 0:00:01
Collecting networkx>=2.0
  Downloading https://files.pythonhosted.org/packages/41/8f/dd6a8e85946def36e4f2c69c84219af0fa5e832b018c970e92f2ad337e45/networkx-2.4-py3-none-any.whl (1.6MB)
     |████████████████████████████████| 1.6MB 230kB/s eta 0:00:01
Requirement already satisfied: matplotlib!=3.0.0,>=2.0.0 in /home/am/.local/lib/python3.6/site-packages (from scikit-image->selectivesearch->pdftotree) (3.1.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/am/.local/lib/python3.6/site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image->selectivesearch->pdftotree) (1.1.0)
Requirement already satisfied: cycler>=0.10 in /home/am/.local/lib/python3.6/site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image->selectivesearch->pdftotree) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /home/am/.local/lib/python3.6/site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image->selectivesearch->pdftotree) (2.4.2)
Building wheels for collected packages: sklearn, selectivesearch
  Building wheel for sklearn (setup.py) ... done
  Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=2397 sha256=6bea32b78642820b5d28914ed55e9341fc8d72d8215623f14159e741afafdac2
  Stored in directory: /home/am/.cache/pip/wheels/76/03/bb/589d421d27431bcd2c6da284d5f2286c8e3b2ea3cf1594c074
  Building wheel for selectivesearch (setup.py) ... done
  Created wheel for selectivesearch: filename=selectivesearch-0.4-cp36-none-any.whl size=5230 sha256=09deb88c9cca9375836c3e64bc52c2b6e6d4a4650034cf921799496ef19e50b8
  Stored in directory: /home/am/.cache/pip/wheels/ab/a0/bd/a56e017d10730401fce75f62ff9364004368b0b96f12c026ba
Successfully built sklearn selectivesearch
Installing collected packages: keras, wand, joblib, scikit-learn, sklearn, imageio, PyWavelets, networkx, scikit-image, selectivesearch, pdftotree
Successfully installed PyWavelets-1.1.1 imageio-2.6.1 joblib-0.14.0 keras-2.0.8 networkx-2.4 pdftotree-0.4.0 scikit-image-0.16.2 scikit-learn-0.21.3 selectivesearch-0.4 sklearn-0.0 wand-0.5.7
Note: you may need to restart the kernel to use updated packages.

In [31]:
from tika import parser

raw = parser.from_file("new.pdf")
raw = str(raw)

safe_text = raw.encode('utf-8', errors='ignore')

safe_text = str(safe_text).replace("\n", "").replace("\\", "")
print('--- safe text ---' )
print( safe_text[0] )

--- safe text ---
b

In [53]:
import tabula 
tables = tabula.read_pdf('new.pdf', guess=False,pages = "all", multiple_tables = True)
tables

In [64]:

tables = camelot.read_pdf('new.pdf', pages = "all")

In [98]:
from wkhtmltopdf import HTMLURLToPDF

make_pdf = HTMLURLToPDF(
    url='http://www.google.com',
    output_file='~/example.pdf',
)
make_pdf.render()

ModuleNotFoundError: No module named 'main'

In [269]:
import pandas as pd
import tabula 
tabula.convert_into("new.pdf", "output.csv", output_format="csv", guess=False)
df=pd.read_csv('output.csv')

In [271]:
df.fillna(' ')

,Consolidated Account Statement,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,01-Apr-1990 To 24-Oct-2019,,,,,,
1,Email Id: bhardwaj.mukesh91@gmail.com This Con...,to you,,,as an,,investor
2,"friendly initiative by CAMS, Karvy, FTAMIL and","SBFS,",,,and,lists,the
3,"Mukesh Sharma transactions, balances and valua...",Funds,in,,which,,you are
4,holding investments. The consolidation has bee...,,,,,,
5,email id entered by you. If you have not enter...,,,,,,
6,H NO 820 GALI NO 6 BATALA ROAD,,,,,,
7,email id is common to several members of your ...,,,,,,
8,NEW RAJESH NAGAR consolidate all those investm...,,,,,,
9,AMRITSAR - 143001,,,,,,
10,Punjab If you find any folios missing from thi...,,,,you have,,not
11,Phone Res: 8054619283 registered your email id...,,,,,,
12,Date Transaction Amount Units Price,,,,,,Unit
13,(INR) (INR),,,,,,Balance
14,HDFC Mutual Fund,,,,,,
15,Folio No: 16033544 / 19,,,,,,
16,HACG1G-HDFC Small Cap Fund - Direct Growth Pla...,,,,Registrar : CAMS,,
17,Opening Unit Balance: 0.000,,,,,,
18,"18-Jul-2019 Purchase 5,000.00 114.597 43.631",,,,,,114.597
19,"16-Aug-2019 Purchase 1,000.00 24.589 40.668",,,,,,139.186
20,"16-Sep-2019 Purchase 1,000.00 24.159 41.392",,,,,,163.345
21,"15-Oct-2019 Purchase 1,000.00 24.693 40.497",,,,,,188.038
22,Closing Unit Balance: 188.038 NAV on 24-Oct-20...,,,,,,
23,*Due to change in fundamental attributes of th...,,,,,,
24,predominantly investing in small cap stocks. C...,,,,,,
25,the allotment date; No Exit Load if units are ...,,,,,,
26,prevailing at the time of allotment of the uni...,,,,,,
27,: 27AAATH1809A1Z9,,,,,,
28,MOTILAL OSWAL MUTUAL FUND,,,,,,
29,Folio No: 91013119452 / 0 KYC: NOT OK PAN: NO...,,,,,,
30,127CPGDG-Motilal Oswal Multicap 35 Fund - Dire...,,Registrar : KARVY,,,,
31,Opening Unit Balance: 0.000,,,,,,
32,"18-Jul-2019 Purchase(NAV Dt : 18/07/2019) 1,00...",,,,,,36.790
33,"16-Aug-2019 Purchase(NAV Dt : 16/08/2019) 1,00...",,,,,,75.290
34,"16-Sep-2019 Purchase(NAV Dt : 16/09/2019) 1,00...",,,,,,113.235
35,"15-Oct-2019 Purchase(NAV Dt : 15/10/2019) 1,00...",,,,,,149.680
36,Closing Unit Balance: 149.680 NAV on 24-Oct-20...,,,,,,
37,"Entry Load: Nil, Exit Load: For subscriptions ...",,,,,,
38,after 15 days fromthe date of allotment. A swi...,,,,,,
39,Systematic Withdrawal of units would bedone on...,,,,,,
40,structure as may have been applicable at the t...,,,,,,
41,structure applicable as of the registration date.,,,,,,
42,CAMSCASWS-02111914452 Version:V3.4 Live-1000,,,,,,

In [450]:
df[14:44]

,Consolidated Account Statement,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
14,HDFC Mutual Fund,NaN,NaN,NaN,NaN,NaN,NaN
15,Folio No: 16033544 / 19,NaN,NaN,NaN,NaN,NaN,NaN
16,HACG1G-HDFC Small Cap Fund - Direct Growth Pla...,NaN,NaN,NaN,Registrar : CAMS,NaN,NaN
17,Opening Unit Balance: 0.000,NaN,NaN,NaN,NaN,NaN,NaN
18,"18-Jul-2019 Purchase 5,000.00 114.597 43.631",NaN,NaN,NaN,NaN,NaN,114.597
19,"16-Aug-2019 Purchase 1,000.00 24.589 40.668",NaN,NaN,NaN,NaN,NaN,139.186
20,"16-Sep-2019 Purchase 1,000.00 24.159 41.392",NaN,NaN,NaN,NaN,NaN,163.345
21,"15-Oct-2019 Purchase 1,000.00 24.693 40.497",NaN,NaN,NaN,NaN,NaN,188.038
22,Closing Unit Balance: 188.038 NAV on 24-Oct-20...,NaN,NaN,NaN,NaN,NaN,NaN
23,*Due to change in fundamental attributes of th...,NaN,NaN,NaN,NaN,NaN,NaN
24,predominantly investing in small cap stocks. C...,NaN,NaN,NaN,NaN,NaN,NaN
25,the allotment date; No Exit Load if units are ...,NaN,NaN,NaN,NaN,NaN,NaN
26,prevailing at the time of allotment of the uni...,NaN,NaN,NaN,NaN,NaN,NaN
27,: 27AAATH1809A1Z9,NaN,NaN,NaN,NaN,NaN,NaN
28,MOTILAL OSWAL MUTUAL FUND,NaN,NaN,NaN,NaN,NaN,NaN
29,Folio No: 91013119452 / 0 KYC: NOT OK PAN: NO...,NaN,NaN,NaN,NaN,NaN,NaN
30,127CPGDG-Motilal Oswal Multicap 35 Fund - Dire...,NaN,Registrar : KARVY,NaN,NaN,NaN,NaN
31,Opening Unit Balance: 0.000,NaN,NaN,NaN,NaN,NaN,NaN
32,"18-Jul-2019 Purchase(NAV Dt : 18/07/2019) 1,00...",NaN,NaN,NaN,NaN,NaN,36.790
33,"16-Aug-2019 Purchase(NAV Dt : 16/08/2019) 1,00...",NaN,NaN,NaN,NaN,NaN,75.290
34,"16-Sep-2019 Purchase(NAV Dt : 16/09/2019) 1,00...",NaN,NaN,NaN,NaN,NaN,113.235
35,"15-Oct-2019 Purchase(NAV Dt : 15/10/2019) 1,00...",NaN,NaN,NaN,NaN,NaN,149.680
36,Closing Unit Balance: 149.680 NAV on 24-Oct-20...,NaN,NaN,NaN,NaN,NaN,NaN
37,"Entry Load: Nil, Exit Load: For subscriptions ...",NaN,NaN,NaN,NaN,NaN,NaN
38,after 15 days fromthe date of allotment. A swi...,NaN,NaN,NaN,NaN,NaN,NaN
39,Systematic Withdrawal of units would bedone on...,NaN,NaN,NaN,NaN,NaN,NaN
40,structure as may have been applicable at the t...,NaN,NaN,NaN,NaN,NaN,NaN
41,structure applicable as of the registration date.,NaN,NaN,NaN,NaN,NaN,NaN
42,CAMSCASWS-02111914452 Version:V3.4 Live-1000,NaN,NaN,NaN,NaN,NaN,NaN

In [149]:
hdfc=df.drop(['Unnamed: 1','Unnamed: 2','Unnamed: 3','Unnamed: 4','Unnamed: 5'],axis=1)[14:22]

In [188]:
d={}
j=0
for i in hdfc['Consolidated Account Statement']:
    if j==0:
        d['Fund']=i
    elif j==1:
        d[i.split(':')[0].strip()]=i.split(':')[1].strip()
    elif j==2:
        d['fund_key']=i.split('(')[0].strip()
        d[i.split('(')[1].split(':')[0]]=i.split('(')[1].split(':')[1].strip(')')
    elif j==3:
        d[i.split(':')[0].strip()]=i.split(':')[1].strip()
    elif j==4:
        d['1st']=i

        
        
        
    j+=1

In [189]:
d

{'Fund': 'HDFC Mutual Fund',
 'Folio No': '16033544 / 19',
 'fund_key': 'HACG1G-HDFC Small Cap Fund - Direct Growth Plan',
 'Advisor': ' INZ000031633',
 'Opening Unit Balance': '0.000',
 '1st': '18-Jul-2019 Purchase 5,000.00 114.597 43.631'}

In [454]:
m=0
k=0
for i in df['Consolidated Account Statement'][m:]:
    for j in i.split():
        if j=="Plan":
            l=k-2
            for i in df['Consolidated Account Statement']:
                print(df['Consolidated Account Statement'][l])
                l+=1
                if df['Consolidated Account Statement'][l].split()[0]=="Closing":
                    print(df['Consolidated Account Statement'][l])
                    m=l
                    break

        
    k+=1
o=m
for i in df['Consolidated Account Statement'][m:]:
    for j in i.split():
        if j=="Fund":
            l=o-2
            for i in df['Consolidated Account Statement']:
                print(df['Consolidated Account Statement'][l])
                l+=1
                if df['Consolidated Account Statement'][l].split()[0]=="Closing":
                    print(df['Consolidated Account Statement'][l])
                    m=l
                    break

        
    o+=1

HDFC Mutual Fund
Folio No: 16033544 / 19
HACG1G-HDFC Small Cap Fund - Direct Growth Plan (Advisor: INZ000031633)
Opening Unit Balance: 0.000
18-Jul-2019 Purchase 5,000.00 114.597 43.631
16-Aug-2019 Purchase 1,000.00 24.589 40.668
16-Sep-2019 Purchase 1,000.00 24.159 41.392
15-Oct-2019 Purchase 1,000.00 24.693 40.497
Closing Unit Balance: 188.038 NAV on 24-Oct-2019: INR 41.689 Valuation on 24-Oct-2019: INR 7,839.12
MOTILAL OSWAL MUTUAL FUND
Folio No: 91013119452 / 0 KYC: NOT OK  PAN: NOT OK
127CPGDG-Motilal Oswal Multicap 35 Fund - Direct Growth(Advisor: INZ000031633)
Opening Unit Balance: 0.000
18-Jul-2019 Purchase(NAV Dt : 18/07/2019) 1,000.00 36.790 27.1814
16-Aug-2019 Purchase(NAV Dt : 16/08/2019) 1,000.00 38.500 25.9742
16-Sep-2019 Purchase(NAV Dt : 16/09/2019) 1,000.00 37.945 26.3536
15-Oct-2019 Purchase(NAV Dt : 15/10/2019) 1,000.00 36.445 27.4383
Closing Unit Balance: 149.680 NAV on 24-Oct-2019: INR 27.9703 Valuation on 24-Oct-2019: INR 4,186.59

In [448]:
m=0
k=0
try:
    for i in df['Consolidated Account Statement'][m:]:
        for j in i.split():
            if j=="Plan":
                l=k-2
                for i in df['Consolidated Account Statement']:
                    print(df['Consolidated Account Statement'][l])
                    l+=1
                    if df['Consolidated Account Statement'][l].split()[0]=="Closing":
                        print(df['Consolidated Account Statement'][l])
                        l+=6
        k+=1
except:
    pass

HDFC Mutual Fund
Folio No: 16033544 / 19
HACG1G-HDFC Small Cap Fund - Direct Growth Plan (Advisor: INZ000031633)
Opening Unit Balance: 0.000
18-Jul-2019 Purchase 5,000.00 114.597 43.631
16-Aug-2019 Purchase 1,000.00 24.589 40.668
16-Sep-2019 Purchase 1,000.00 24.159 41.392
15-Oct-2019 Purchase 1,000.00 24.693 40.497
Closing Unit Balance: 188.038 NAV on 24-Oct-2019: INR 41.689 Valuation on 24-Oct-2019: INR 7,839.12
MOTILAL OSWAL MUTUAL FUND
Folio No: 91013119452 / 0 KYC: NOT OK  PAN: NOT OK
127CPGDG-Motilal Oswal Multicap 35 Fund - Direct Growth(Advisor: INZ000031633)
Opening Unit Balance: 0.000
18-Jul-2019 Purchase(NAV Dt : 18/07/2019) 1,000.00 36.790 27.1814
16-Aug-2019 Purchase(NAV Dt : 16/08/2019) 1,000.00 38.500 25.9742
16-Sep-2019 Purchase(NAV Dt : 16/09/2019) 1,000.00 37.945 26.3536
15-Oct-2019 Purchase(NAV Dt : 15/10/2019) 1,000.00 36.445 27.4383
Closing Unit Balance: 149.680 NAV on 24-Oct-2019: INR 27.9703 Valuation on 24-Oct-2019: INR 4,186.59
CAMSCASWS-02111914452 Version:V3.4 Live-1000

In [541]:
data=[]
f_data=[]
m=0
k=0
try:
    for i in df['Consolidated Account Statement'][m:]:
        for j in i.split():
            if j=="Plan":
                l=k-2 
                temp1=[]
                data.append(temp1)
                for i in df['Consolidated Account Statement']:
                    
                    #print(df['Consolidated Account Statement'][l])
                    temp1.append(df['Consolidated Account Statement'][l])
                    
                    l+=1
                    if df['Consolidated Account Statement'][l].split()[0]=="Closing":
                        #print(df['Consolidated Account Statement'][l])
                        temp1.append(df['Consolidated Account Statement'][l])
                        data.append(temp1)
                        l+=6
                        temp1=[]
                        
        k+=1
except:
    pass
[f_data.append(i) for i in data if i not in f_data]
f_data

[['HDFC Mutual Fund',
  'Folio No: 16033544 / 19',
  'HACG1G-HDFC Small Cap Fund - Direct Growth Plan (Advisor: INZ000031633)',
  'Opening Unit Balance: 0.000',
  '18-Jul-2019 Purchase 5,000.00 114.597 43.631',
  '16-Aug-2019 Purchase 1,000.00 24.589 40.668',
  '16-Sep-2019 Purchase 1,000.00 24.159 41.392',
  '15-Oct-2019 Purchase 1,000.00 24.693 40.497',
  'Closing Unit Balance: 188.038 NAV on 24-Oct-2019: INR 41.689 Valuation on 24-Oct-2019: INR 7,839.12'],
 ['MOTILAL OSWAL MUTUAL FUND',
  'Folio No: 91013119452 / 0 KYC: NOT OK  PAN: NOT OK',
  '127CPGDG-Motilal Oswal Multicap 35 Fund - Direct Growth(Advisor: INZ000031633)',
  'Opening Unit Balance: 0.000',
  '18-Jul-2019 Purchase(NAV Dt : 18/07/2019) 1,000.00 36.790 27.1814',
  '16-Aug-2019 Purchase(NAV Dt : 16/08/2019) 1,000.00 38.500 25.9742',
  '16-Sep-2019 Purchase(NAV Dt : 16/09/2019) 1,000.00 37.945 26.3536',
  '15-Oct-2019 Purchase(NAV Dt : 15/10/2019) 1,000.00 36.445 27.4383',
  'Closing Unit Balance: 149.680 NAV on 24-Oct-2019: INR 27.9703 Valuation on 24-Oct-2019: INR 4,186.59']]

In [529]:
f_data = dict([(i, 1) for i in data]).keys()

TypeError: unhashable type: 'list'

In [530]:
a = [1, 2, 3, 3, 5, 9, 6, 2, 8, 5, 2, 3, 5, 7, 3, 5, 8]
b=[]
[b.append(item) for item in a if item not in b]

[None, None, None, None, None, None, None, None]

In [533]:
f_data

[['HDFC Mutual Fund',
  'Folio No: 16033544 / 19',
  'HACG1G-HDFC Small Cap Fund - Direct Growth Plan (Advisor: INZ000031633)',
  'Opening Unit Balance: 0.000',
  '18-Jul-2019 Purchase 5,000.00 114.597 43.631',
  '16-Aug-2019 Purchase 1,000.00 24.589 40.668',
  '16-Sep-2019 Purchase 1,000.00 24.159 41.392',
  '15-Oct-2019 Purchase 1,000.00 24.693 40.497',
  'Closing Unit Balance: 188.038 NAV on 24-Oct-2019: INR 41.689 Valuation on 24-Oct-2019: INR 7,839.12'],
 ['MOTILAL OSWAL MUTUAL FUND',
  'Folio No: 91013119452 / 0 KYC: NOT OK  PAN: NOT OK',
  '127CPGDG-Motilal Oswal Multicap 35 Fund - Direct Growth(Advisor: INZ000031633)',
  'Opening Unit Balance: 0.000',
  '18-Jul-2019 Purchase(NAV Dt : 18/07/2019) 1,000.00 36.790 27.1814',
  '16-Aug-2019 Purchase(NAV Dt : 16/08/2019) 1,000.00 38.500 25.9742',
  '16-Sep-2019 Purchase(NAV Dt : 16/09/2019) 1,000.00 37.945 26.3536',
  '15-Oct-2019 Purchase(NAV Dt : 15/10/2019) 1,000.00 36.445 27.4383',
  'Closing Unit Balance: 149.680 NAV on 24-Oct-2019: INR 27.9703 Valuation on 24-Oct-2019: INR 4,186.59']]

In [143]:
import pandas as pd
import tabula 
tabula.convert_into("new.pdf", "output.csv", output_format="csv", guess=False)
df=pd.read_csv('output.csv')
data=[]
f_data=[]
m=0
k=0
try:
    for i in df['Consolidated Account Statement'][m:]:
        for j in i.split():
            if j=="Plan":
                l=k-2 
                temp1=[]
                data.append(temp1)
                for i in df['Consolidated Account Statement']:
                    
                    #print(df['Consolidated Account Statement'][l])
                    temp1.append(df['Consolidated Account Statement'][l])
                    
                    l+=1
                    if df['Consolidated Account Statement'][l].split()[0]=="Closing":
                        #print(df['Consolidated Account Statement'][l])
                        temp1.append(df['Consolidated Account Statement'][l])
                        data.append(temp1)
                        l+=6
                        temp1=[]
                        
        k+=1
except:
    pass
[f_data.append(i) for i in data if i not in f_data]

[None, None]

In [142]:
json_final={}
json_final['item']=[]
k=0
for p in range(len(f_data)):
    json_data={}
    for i in range(len(f_data[p])):
        if i==0:
            json_data['id']=p+1
            json_data['Fund']=f_data[p][i]
        if i==1:
            if len(f_data[p][i].split(':')[1].strip().split())>=4:
                a=f_data[p][i].split(':')[1].strip().split()
                a=''.join(a[0:-1])   
                json_data[f_data[p][i].split(':')[0].strip()]=a
            else:
                json_data[f_data[p][i].split(':')[0].strip()]=f_data[p][i].split(':')[1].strip()
                
        if i==2:
            #print(p)
            json_data['sub_fund']=f_data[p][i].split('(')[0].strip()
            json_data[f_data[p][i].split('(')[1].split(':')[0]]=f_data[p][i].split('(')[1].split(':')[1].strip(')')
        if i==3:
            json_data[f_data[p][i].split(':')[0].strip()]=f_data[p][i].split(':')[1].strip()
        try:
            if i==4:
                o=1
                txn=[]
                t=0
                for m in f_data[p][4:]: 
                    if m.split(' ')[0]=='Closing':
                        break
                    json_data['txn'+str(o)]={}
                    json_data['txn'+str(o)]['Date']=m.split(' ')[0].strip()
                    json_data['txn'+str(o)]['Amount']=m.split(' ')[-3].strip()
                    json_data['txn'+str(o)]['units']=m.split(' ')[-2].strip()
                    json_data['txn'+str(o)]['price']=m.split(' ')[-1].strip()
                    if t>=1:
                        ub=float(m.split(' ')[-2].strip())+float(txn[-1])
                        u_b='%.3f'%ub
                        json_data['txn'+str(o)]['UnitBalance']=u_b
                        txn.append(u_b)
                    else:
                        json_data['txn'+str(o)]['UnitBalance']=m.split(' ')[-2].strip()
                        txn.append(m.split(' ')[-2].strip())
                    
                    t+=1
                    o+=1
    

        except:
            pass
    json_final['item'].append(json_data)   
json_final

{'item': [{'id': 1,
   'Fund': 'HDFC Mutual Fund',
   'Folio No': '16033544 / 19',
   'sub_fund': 'HACG1G-HDFC Small Cap Fund - Direct Growth Plan',
   'Advisor': ' INZ000031633',
   'Opening Unit Balance': '0.000',
   'txn1': {'Date': '18-Jul-2019',
    'Amount': '5,000.00',
    'units': '114.597',
    'price': '43.631',
    'UnitBalance': '114.597'},
   'txn2': {'Date': '16-Aug-2019',
    'Amount': '1,000.00',
    'units': '24.589',
    'price': '40.668',
    'UnitBalance': '139.186'},
   'txn3': {'Date': '16-Sep-2019',
    'Amount': '1,000.00',
    'units': '24.159',
    'price': '41.392',
    'UnitBalance': '163.345'},
   'txn4': {'Date': '15-Oct-2019',
    'Amount': '1,000.00',
    'units': '24.693',
    'price': '40.497',
    'UnitBalance': '188.038'}},
  {'id': 2,
   'Fund': 'MOTILAL OSWAL MUTUAL FUND',
   'Folio No': '91013119452/0',
   'sub_fund': '127CPGDG-Motilal Oswal Multicap 35 Fund - Direct Growth',
   'Advisor': ' INZ000031633',
   'Opening Unit Balance': '0.000',
   'txn1': {'Date': '18-Jul-2019',
    'Amount': '1,000.00',
    'units': '36.790',
    'price': '27.1814',
    'UnitBalance': '36.790'},
   'txn2': {'Date': '16-Aug-2019',
    'Amount': '1,000.00',
    'units': '38.500',
    'price': '25.9742',
    'UnitBalance': '75.290'},
   'txn3': {'Date': '16-Sep-2019',
    'Amount': '1,000.00',
    'units': '37.945',
    'price': '26.3536',
    'UnitBalance': '113.235'},
   'txn4': {'Date': '15-Oct-2019',
    'Amount': '1,000.00',
    'units': '36.445',
    'price': '27.4383',
    'UnitBalance': '149.680'}}]}

In [144]:
import pandas as pd
import tabula 
tabula.convert_into("new.pdf", "output.csv", output_format="csv", guess=False)
df=pd.read_csv('output.csv')
data=[]
f_data=[]
m=0
k=0
try:
    for i in df['Consolidated Account Statement'][m:]:
        for j in i.split():
            if j=="Plan":
                l=k-2 
                temp1=[]
                data.append(temp1)
                for i in df['Consolidated Account Statement']:
                    
                    #print(df['Consolidated Account Statement'][l])
                    temp1.append(df['Consolidated Account Statement'][l])
                    
                    l+=1
                    if df['Consolidated Account Statement'][l].split()[0]=="Closing":
                        #print(df['Consolidated Account Statement'][l])
                        temp1.append(df['Consolidated Account Statement'][l])
                        data.append(temp1)
                        l+=6
                        temp1=[]
                        
        k+=1
except:
    pass
[f_data.append(i) for i in data if i not in f_data]
json_final={}
json_final['item']=[]
k=0
for p in range(len(f_data)):
    json_data={}
    for i in range(len(f_data[p])):
        if i==0:
            json_data['id']=p+1
            json_data['Fund']=f_data[p][i]
        if i==1:
            if len(f_data[p][i].split(':')[1].strip().split())>=4:
                a=f_data[p][i].split(':')[1].strip().split()
                a=''.join(a[0:-1])   
                json_data[f_data[p][i].split(':')[0].strip()]=a
            else:
                json_data[f_data[p][i].split(':')[0].strip()]=f_data[p][i].split(':')[1].strip()
                
        if i==2:
            #print(p)
            json_data['sub_fund']=f_data[p][i].split('(')[0].strip()
            json_data[f_data[p][i].split('(')[1].split(':')[0]]=f_data[p][i].split('(')[1].split(':')[1].strip(')')
        if i==3:
            json_data[f_data[p][i].split(':')[0].strip()]=f_data[p][i].split(':')[1].strip()
        try:
            if i==4:
                o=1
                txn=[]
                t=0
                for m in f_data[p][4:]: 
                    if m.split(' ')[0]=='Closing':
                        break
                    json_data['txn'+str(o)]={}
                    json_data['txn'+str(o)]['Date']=m.split(' ')[0].strip()
                    json_data['txn'+str(o)]['Amount']=m.split(' ')[-3].strip()
                    json_data['txn'+str(o)]['units']=m.split(' ')[-2].strip()
                    json_data['txn'+str(o)]['price']=m.split(' ')[-1].strip()
                    if t>=1:
                        ub=float(m.split(' ')[-2].strip())+float(txn[-1])
                        u_b='%.3f'%ub
                        json_data['txn'+str(o)]['UnitBalance']=u_b
                        txn.append(u_b)
                    else:
                        json_data['txn'+str(o)]['UnitBalance']=m.split(' ')[-2].strip()
                        txn.append(m.split(' ')[-2].strip())
                    
                    t+=1
                    o+=1
    

        except:
            pass
    json_final['item'].append(json_data)   
json_final

{'item': [{'id': 1,
   'Fund': 'HDFC Mutual Fund',
   'Folio No': '16033544 / 19',
   'sub_fund': 'HACG1G-HDFC Small Cap Fund - Direct Growth Plan',
   'Advisor': ' INZ000031633',
   'Opening Unit Balance': '0.000',
   'txn1': {'Date': '18-Jul-2019',
    'Amount': '5,000.00',
    'units': '114.597',
    'price': '43.631',
    'UnitBalance': '114.597'},
   'txn2': {'Date': '16-Aug-2019',
    'Amount': '1,000.00',
    'units': '24.589',
    'price': '40.668',
    'UnitBalance': '139.186'},
   'txn3': {'Date': '16-Sep-2019',
    'Amount': '1,000.00',
    'units': '24.159',
    'price': '41.392',
    'UnitBalance': '163.345'},
   'txn4': {'Date': '15-Oct-2019',
    'Amount': '1,000.00',
    'units': '24.693',
    'price': '40.497',
    'UnitBalance': '188.038'}},
  {'id': 2,
   'Fund': 'MOTILAL OSWAL MUTUAL FUND',
   'Folio No': '91013119452/0',
   'sub_fund': '127CPGDG-Motilal Oswal Multicap 35 Fund - Direct Growth',
   'Advisor': ' INZ000031633',
   'Opening Unit Balance': '0.000',
   'txn1': {'Date': '18-Jul-2019',
    'Amount': '1,000.00',
    'units': '36.790',
    'price': '27.1814',
    'UnitBalance': '36.790'},
   'txn2': {'Date': '16-Aug-2019',
    'Amount': '1,000.00',
    'units': '38.500',
    'price': '25.9742',
    'UnitBalance': '75.290'},
   'txn3': {'Date': '16-Sep-2019',
    'Amount': '1,000.00',
    'units': '37.945',
    'price': '26.3536',
    'UnitBalance': '113.235'},
   'txn4': {'Date': '15-Oct-2019',
    'Amount': '1,000.00',
    'units': '36.445',
    'price': '27.4383',
    'UnitBalance': '149.680'}}]}

In [147]:
import tabula 
import easygui
from PyPDF2 import PdfFileReader, PdfFileWriter

#encrypt passwrod protect file
#####################################--Unlock--#######################################################
file_path = easygui.fileopenbox()
password='KSTPS1360G'
file_name=input('Enter File Name')
with open(file_path, 'rb') as input_file, \
    open(file_name+'.pdf', 'wb') as output_file:
    reader = PdfFileReader(input_file)
    reader.decrypt(password)
    writer = PdfFileWriter()
    for i in range(reader.getNumPages()):
        writer.addPage(reader.getPage(i))
    writer.write(output_file)
#######################################--READ DATA--##################################################
df=tabula.read_pdf(file_name+'.pdf',guess=False)
data=[]
f_data=[]
m=0
k=0
try:
    for i in df['Consolidated Account Statement'][m:]:
        for j in i.split():
            if j=="Plan":
                l=k-2 
                temp1=[]
                data.append(temp1)
                for i in df['Consolidated Account Statement']:
                    
                    #print(df['Consolidated Account Statement'][l])
                    temp1.append(df['Consolidated Account Statement'][l])
                    
                    l+=1
                    if df['Consolidated Account Statement'][l].split()[0]=="Closing":
                        #print(df['Consolidated Account Statement'][l])
                        temp1.append(df['Consolidated Account Statement'][l])
                        data.append(temp1)
                        l+=6
                        temp1=[]
                        
        k+=1
except:
    pass
[f_data.append(i) for i in data if i not in f_data]
json_final={}
json_final['item']=[]
k=0
for p in range(len(f_data)):
    json_data={}
    for i in range(len(f_data[p])):
        if i==0:
            json_data['id']=p+1
            json_data['Fund']=f_data[p][i]
        if i==1:
            if len(f_data[p][i].split(':')[1].strip().split())>=4:
                a=f_data[p][i].split(':')[1].strip().split()
                a=''.join(a[0:-1])   
                json_data[f_data[p][i].split(':')[0].strip()]=a
            else:
                json_data[f_data[p][i].split(':')[0].strip()]=f_data[p][i].split(':')[1].strip()
                
        if i==2:
            #print(p)
            json_data['sub_fund']=f_data[p][i].split('(')[0].strip()
            json_data[f_data[p][i].split('(')[1].split(':')[0]]=f_data[p][i].split('(')[1].split(':')[1].strip(')')
        if i==3:
            json_data[f_data[p][i].split(':')[0].strip()]=f_data[p][i].split(':')[1].strip()
        try:
            if i==4:
                o=1
                txn=[]
                t=0
                for m in f_data[p][4:]: 
                    if m.split(' ')[0]=='Closing':
                        break
                    json_data['txn'+str(o)]={}
                    json_data['txn'+str(o)]['Date']=m.split(' ')[0].strip()
                    json_data['txn'+str(o)]['Amount']=m.split(' ')[-3].strip()
                    json_data['txn'+str(o)]['units']=m.split(' ')[-2].strip()
                    json_data['txn'+str(o)]['price']=m.split(' ')[-1].strip()
                    if t>=1:
                        ub=float(m.split(' ')[-2].strip())+float(txn[-1])
                        u_b='%.3f'%ub
                        json_data['txn'+str(o)]['UnitBalance']=u_b
                        txn.append(u_b)
                    else:
                        json_data['txn'+str(o)]['UnitBalance']=m.split(' ')[-2].strip()
                        txn.append(m.split(' ')[-2].strip())
                    
                    t+=1
                    o+=1
    

        except:
            pass
    json_final['item'].append(json_data)   
json_final

Enter File Nameoutput

{'item': [{'id': 1,
   'Fund': 'HDFC Mutual Fund',
   'Folio No': '16033544 / 19',
   'sub_fund': 'HACG1G-HDFC Small Cap Fund - Direct Growth Plan',
   'Advisor': ' INZ000031633',
   'Opening Unit Balance': '0.000',
   'txn1': {'Date': '18-Jul-2019',
    'Amount': '5,000.00',
    'units': '114.597',
    'price': '43.631',
    'UnitBalance': '114.597'},
   'txn2': {'Date': '16-Aug-2019',
    'Amount': '1,000.00',
    'units': '24.589',
    'price': '40.668',
    'UnitBalance': '139.186'},
   'txn3': {'Date': '16-Sep-2019',
    'Amount': '1,000.00',
    'units': '24.159',
    'price': '41.392',
    'UnitBalance': '163.345'},
   'txn4': {'Date': '15-Oct-2019',
    'Amount': '1,000.00',
    'units': '24.693',
    'price': '40.497',
    'UnitBalance': '188.038'}},
  {'id': 2,
   'Fund': 'MOTILAL OSWAL MUTUAL FUND',
   'Folio No': '91013119452/0',
   'sub_fund': '127CPGDG-Motilal Oswal Multicap 35 Fund - Direct Growth',
   'Advisor': ' INZ000031633',
   'Opening Unit Balance': '0.000',
   'txn1': {'Date': '18-Jul-2019',
    'Amount': '1,000.00',
    'units': '36.790',
    'price': '27.1814',
    'UnitBalance': '36.790'},
   'txn2': {'Date': '16-Aug-2019',
    'Amount': '1,000.00',
    'units': '38.500',
    'price': '25.9742',
    'UnitBalance': '75.290'},
   'txn3': {'Date': '16-Sep-2019',
    'Amount': '1,000.00',
    'units': '37.945',
    'price': '26.3536',
    'UnitBalance': '113.235'},
   'txn4': {'Date': '15-Oct-2019',
    'Amount': '1,000.00',
    'units': '36.445',
    'price': '27.4383',
    'UnitBalance': '149.680'}}]}